### ISSUE TITLE
Implement  LU decomposition algorithm without MPI (one computer)

### ISSUE THREAD

**Issue by lukasz22** [tbajorek/LUdecoMPI#7]

**Comment by tbajorek** [comment]
Please realize this functionality as soon as possible because it's necessary to finish the whole project before April 25. I hope The deadline will be met. This is really big and important problem. Maybe this milestone can help with that. I offer my help. I just would like to get to know the schedule of this project to  calm myself and to remove my fears. I expected it will be done after Easter, of course this year. It wasn't happened already. Please to treat it seriously with a proper priority, without useless paperwork.
Best regards,
Tomasz Bajorek

**Comment by tbajorek** [comment]
I guess it works. We can start a next part of our task.
